# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5605baaafa8f9d5eedbdcb12412708cd214b43a10916569d2cdef45cc0657cf6ea51518bbc02705253ee3ea1c6dba1caacce44a136b0d4226413c8b76bd60724

test:
  secret_key_base: 5ccfc3d829ead5ff2e5a0e2d6e0ba01df41b4abcce8b365ab49f21b28ec0db9dd8d9c313c8c6021869879b6c8800d6a6a0944df34ab2031523ca6000c5f02d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
